using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Coomuce.GestorReportes.Modelo
{
    public class ReporteHistoriaIndividual
    {
        public DateTime fechaVisitaHfdfr { get; set; }

        public string horaInicio { get; set; }
        public string horaFin { get; set; }
        public string nombreDepartamento { get; set; }
        public string nombreCiudad { get; set; }
        public string vereda { get; set; }
        public string barrio { get; set; }
        public string telefono { get; set; }
        public string primerNombreFuanAfiliado { get; set; }
        public string segundoNombreFuanAfiliado { get; set; }
        public string primerApellidoFuanAfiliado { get; set; }
        public string segundoApellidoFuanAfiliado { get; set; }
        public string nombreCompleto { get; set; }        
        public string codigoTipoIdentificacion { get; set; }
        public string identificacionFuanAfiliado { get; set; }
        public string numCarnetFuanAfiliado { get; set; }
        public string sisben { get; set; }
        public string procedenciaRural { get; set; }
        public string procedenciaUrbano { get; set; }
        public string procedenciaDesplazadoViolencia { get; set; }
        public string procedenciaIndigena { get; set; }
        public string procedenciaOtroPais { get; set; }
        public string ubicacionRural { get; set; }
        public string ubicacionUrbano { get; set; }
        public string ubicacionDesplazado { get; set; }
        public string numeroPersonasDomicilio { get; set; }
        public string numeroPersonas618 { get; set; }
        public string numeroPersonas618Estudian { get; set; }
        public string numeroPersonas614 { get; set; }
        public string numeroPersonas614Trabajan { get; set; }
        public string aportaMadre { get; set; }
        public string aportaPadre { get; set; }
        public string aportaHijos { get; set; }
        public string aportaOtro { get; set; }
        public string numeroPersonasmayores65 { get; set; }
        public string numeroPersonasmayores65Trabajan { get; set; }
        public string numeroPersonas1565 { get; set; }
        public string numeroPersonas1565trabajan { get; set; }
        public string totalIngresosFamilia { get; set; }
        public string primariaIncompletaMadre { get; set; }
        public string primariaIncompletaPadre { get; set; }
        public string primariaCompletaMadre { get; set; }
        public string primariaCompletaPadre { get; set; }
        public string bachilleratoIncompletaMadre { get; set; }
        public string bachilleratoIncompletaPadre { get; set; }
        public string bachilleratoCompletaMadre { get; set; }
        public string bachilleratoCompletaPadre { get; set; }
        public string tecnicosCompletaMadre { get; set; }
        public string tecnicosCompletaPadre { get; set; }
        public string universitariosMadre { get; set; }
        public string universitariosPadre { get; set; }
        public string educacionNoFormalMadre { get; set; }
        public string educacionNoFormalPadre { get; set; }
        public string otrosMadre { get; set; }
        public string otrosPadre { get; set; }
        public string ningunEstudioMadre { get; set; }
        public string ningunEstudioPadre { get; set; }
        public string pisoBloque { get; set; }
        public string pisoTierra { get; set; }
        public string pisoCemento { get; set; }
        public string pisoBaldosa { get; set; }
        public string pisoMadera { get; set; }
        public string pisoCarton { get; set; }
        public string pisoPrefabricado { get; set; }
        public string pisoAdobe { get; set; }
        public string pisoGuadua { get; set; }
        public string pisoParoy { get; set; }
        public string pisoZing { get; set; }
        public string pisoPalma { get; set; }
        public string pisoBarro { get; set; }
        public string pisoLadrillo { get; set; }
        public string pisoOtro { get; set; }
        public string techoBloque { get; set; }
        public string techoTierra { get; set; }
        public string techoCemento { get; set; }
        public string techoBaldosa { get; set; }
        public string techoMadera { get; set; }
        public string techoCarton { get; set; }
        public string techoPrefabricado { get; set; }
        public string techoAdobe { get; set; }
        public string techoGuadua { get; set; }
        public string techoParoy { get; set; }
        public string techoZing { get; set; }
        public string techoPalma { get; set; }
        public string techoBarro { get; set; }
        public string techoLadrillo { get; set; }
        public string techoOtro { get; set; }
        public string paredesBloque { get; set; }
        public string paredesTierra { get; set; }
        public string paredesCemento { get; set; }
        public string paredesBaldosa { get; set; }
        public string paredesMadera { get; set; }
        public string paredesCarton { get; set; }
        public string paredesPrefabricado { get; set; }
        public string paredesAdobe { get; set; }
        public string paredesGuadua { get; set; }
        public string paredesParoy { get; set; }
        public string paredesZing { get; set; }
        public string paredesPalma { get; set; }
        public string paredesBarro { get; set; }
        public string paredesLadrillo { get; set; }
        public string paredesOtro { get; set; } 
        public string numeroHabitaciones { get; set; }
        public string numeroCamasDomicilio { get; set; }
        public string tipoViviendaCasa { get; set; }
        public string tipoViviendaApartamento { get; set; }
        public string tipoViviendaCuarto { get; set; }
        public string tipoViviendaAlbergue { get; set; }
        public string tipoViviendaHabitanteCalle { get; set; }
        public string tenenciaPropia { get; set; }
        public string tenenciaArriendo { get; set; }
        public string tenenciaFamiliar { get; set; }
        public string tenenciaNinguna { get; set; }
        public string familiaCocinaDuermeSi { get; set; }
        public string familiaCocinaDuermeNo { get; set; }
        public string familiaCocinaDuermeNa { get; set; }
        public string combustibleLena { get; set; }
        public string combustibleCarbon { get; set; }
        public string combustibleElectricidad { get; set; }
        public string combustibleGas { get; set; }
        public string combustibleGasolina { get; set; }
        public string combustiblePetroleo { get; set; }
        public string combustibleOtro { get; set; }
        public string combustibleNoAplica { get; set; }
        public string tratamientoAguaNo { get; set; }
        public string tratamientoAguaClorada { get; set; }
        public string tratamientoAguaFiltrada { get; set; }
        public string tratamientoAguaHervida { get; set; }
        public string recipientesDesinfectadosSi { get; set; }
        public string recipientesDesinfectadosNo { get; set; }
        public string recipientesDesinfectadosNa { get; set; }
        public string viviendaServicioLuz { get; set; }
        public string viviendaServicioAgua { get; set; }
        public string viviendaServicioTelefono { get; set; }
        public string viviendaServicioAlcantarillado { get; set; }
        public string viviendaServicioRecoleccionBasura { get; set; }
        public string viviendaServicioNoAplica { get; set; } //VAMOS ACA
        public string dispoExcresasLetrina { get; set; }
        public string dispoExcresasSanitarioAlcantarillado { get; set; }
        public string dispoExcresasSanitarioPozo { get; set; }
        public string dispoExcresasInodoroSinConexion { get; set; }
        public string dispoExcresasNoSanitario { get; set; }
        public string manejoBasurasAdecuado { get; set; }
        public string manejoBasurasInadecuado { get; set; }
        public string manejoBasurasNoAplica { get; set; }
        public string disposicionBasuraQuema { get; set; }
        public string disposicionBasuraEntierra { get; set; }
        public string disposicionBasuraArrojaRio { get; set; }
        public string disposicionBasuraAireLibre { get; set; }
        public string disposicionBasuraRecogeServicio { get; set; }
        public string disposicionBasuraOtro { get; set; }
        public string frDispInadecuadaBasura { get; set; }
        public string frAreneras { get; set; }
        public string frInundaciones { get; set; }
        public string frPandillismo { get; set; }
        public string frViolencia { get; set; }
        public string frCanosRiosContaminados { get; set; }
        public string frCarboneras { get; set; }
        public string frInseguridad { get; set; }
        public string frDrogadiccion { get; set; }
        public string frOtro { get; set; }
        public string frDeslizamientoTierra { get; set; }
        public string frRoedores { get; set; }
        public string frInsectos { get; set; }
        public string frProstitucion { get; set; }
        public string frAlcoholismo { get; set; }
        public string frNinguna { get; set; }
        public string animalesSi { get; set; }
        public string animalesNo { get; set; }
        public string numeroCaninos { get; set; }
        public string numeroAves { get; set; }
        public string numeroPorcinos { get; set; }
        public string numeroOvinos { get; set; }
        public string numeroEquinos { get; set; }
        public string numeroRoedores { get; set; }
        public string numeroOfidios { get; set; }
        public string numeroFelinos { get; set; }
        public string numeroBovinos { get; set; }
        public string numeroOtros { get; set; }
        public string numeroNa { get; set; }
        public string vacunadoCaninos { get; set; }
        public string vacunadoAves { get; set; }
        public string vacunadoPorcinos { get; set; }
        public string vacunadoOvinos { get; set; }
        public string vacunadoEquinos { get; set; }
        public string vacunadoFelinos { get; set; }
        public List<Pregunta28> discapacitados { get; set; }
        public string numeroNoControlOdontologico { get; set; }
        public string mujer60SinControlMedico { get; set; }
        public string hombre60SinControlMedico { get; set; }
        public string na60SinControlMedico { get; set; }
        public List<Pregunta31> integrantesEspectoracion { get; set; }
        public List<Pregunta32> integrantesManchasPiel { get; set; }
        public List<Pregunta33> integrantesEnfermosVisita { get; set; }
        public string corrigeCompCastigoFisico { get; set; }
        public string corrigeCompRegano { get; set; }
        public string corrigeCompEncierro { get; set; }
        public string corrigeCompZarandeo { get; set; }
        public string corrigeCompPrivacion { get; set; }
        public string corrigeCompDialogo { get; set; }
        public string corrigeCompAislamiento { get; set; }
        public string corrigeCompOtro { get; set; }
        public string nino12cocinaSi { get; set; }
        public string nino12cocinaNo { get; set; }
        public string conflictosHogarSi { get; set; }
        public string conflictosHogarNo { get; set; }
        public string solConflictosDialogando { get; set; }
        public string solConflictosAgresionFisica { get; set; }
        public string solConflictosPrivacionEconomica { get; set; }
        public string solConflictosAgresionVerbal { get; set; }
        public string solConflictosPrivacion { get; set; }
        public string solConflictosAgresionSexual { get; set; }
        public string solConflictosOtros { get; set; }
        public string solConflictosSinDato { get; set; }

        public string agredePapa { get; set; }
        public string agredeMama { get; set; }
        public string agredeHijos { get; set; }
        public string agredePadrastro { get; set; }
        public string agredeNoClaro { get; set; }
        public string agredeNoAplica { get; set; }
        public string actividadesFamiliaDeportivas { get; set; }
        public string actividadesFamiliaEspirituales { get; set; }
        public string actividadesFamiliaRecreativas { get; set; }
        public string actividadesFamiliaSociales { get; set; }
        public string actividadesFamiliaOtra { get; set; }
        public string actividadesFamiliaNinguna { get; set; }

        public string actividades60FamiliaDeportivas { get; set; }
        public string actividades60FamiliaEspirituales { get; set; }
        public string actividades60FamiliaRecreativas { get; set; }
        public string actividades60FamiliaSociales { get; set; }
        public string actividades60FamiliaOtra { get; set; }
        public string actividades60FamiliaNinguna { get; set; }
        public string comparteMamaSi { get; set; }
        public string comparteMamaNo { get; set; }
        public string comparteMamaAveces { get; set; }
        public string compartePapaSi { get; set; }
        public string compartePapaNo { get; set; }
        public string compartePapaAveces { get; set; }
        public string comparteOtroSi { get; set; }
        public string comparteOtroNo { get; set; }
        public string comparteOtroAveces { get; set; }
        public string comparteNinguno { get; set; }
        public string causaNoComparteTrabajo { get; set; }
        public string causaNoComparteNiñosJueguenSolos { get; set; }
        public string causaNoComparteDescansan { get; set; }
        public string causaNoComparteNoAplica { get; set; }
        public string causaNoComparteOtras { get; set; }
        public string orientacionSexualSi { get; set; }
        public string orientacionSexualNo { get; set; }
        public string orientacionHijosDialogo { get; set; }
        public string orientacionHijosColegio { get; set; }
        public string orientacionHijosNoLoRealiza { get; set; }
        public string tiempoEjercicioEdad { get; set; }
        public string tiempoEjerciciomenos30 { get; set; }
        public string tiempoEjerciciomenos5dias { get; set; }
        public string tiempoEjercicioSemana { get; set; }
        public string tiempoEjercicioNoRealiza { get; set; }
        public string digitadoPor { get; set; }

        public string firmaAfiliado { get; set; }

    }


}