//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsistenciaGeneral()
        {
            this.ListaAsistenciaGeneral = new HashSet<ListaAsistenciaGeneral>();
        }
    
        public int idAsistenciaGeneral { get; set; }
        public short idCiudad { get; set; }
        public byte idGruposFocales { get; set; }
        public string temaAsistenciaGeneral { get; set; }
        public short idModulo { get; set; }
        public string formadorAsistenciaGeneral { get; set; }
        public System.DateTime fechaAsistenciaGeneral { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual GruposFocales GruposFocales { get; set; }
        public virtual Modulo Modulo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaAsistenciaGeneral> ListaAsistenciaGeneral { get; set; }
    }
}
