//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloVitalPreguntasSubFactorRiesgo
    {
        public byte idCicloVital { get; set; }
        public byte idTipoSexo { get; set; }
        public short idPreguntasSubFactorRiesgo { get; set; }
    
        public virtual CicloVital CicloVital { get; set; }
        public virtual PreguntasSubFactorRiesgo PreguntasSubFactorRiesgo { get; set; }
        public virtual TipoSexo TipoSexo { get; set; }
    }
}
