//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionCuerpoCorreo
    {
        public byte idConfiguracionCuerpoCorreo { get; set; }
        public byte tipoConfiguracionCuerpoCorreo { get; set; }
        public string tituloConfiguracionCuerpoCorreo { get; set; }
        public string mensajeConfiguracionCuerpoCorreo { get; set; }
    }
}
