//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionGeneral
    {
        public byte idConfiguracionGeneral { get; set; }
        public byte tiempoInactividadConfiguracionGeneral { get; set; }
        public Nullable<decimal> salarioConfiguracionGeneral { get; set; }
        public string emailSalienteConfiguracionGeneral { get; set; }
        public string pswEmailConfiguracionGeneral { get; set; }
        public string ccConfiguracionGeneral { get; set; }
        public string csConfiguracionGeneral { get; set; }
        public string hostConfiguracionGeneral { get; set; }
        public byte portConfiguracionGeneral { get; set; }
        public bool sslConfiguracionGeneral { get; set; }
    }
}
