//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposicionExcreta
    {
        public byte idDisposicionExcreta { get; set; }
        public string codigoDisposicionExcreta { get; set; }
        public string nombreDisposicionExcreta { get; set; }
    }
}
