//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaIpsRespPregunta
    {
        public int idEncuestaIps { get; set; }
        public short idEncuestaPregunta { get; set; }
        public byte valorEncuestaIpsRespPregunta { get; set; }
    
        public virtual EncuestaIps EncuestaIps { get; set; }
        public virtual EncuestaPregunta EncuestaPregunta { get; set; }
    }
}
