//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaIps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaIps()
        {
            this.EncuestaIpsRespLiteral = new HashSet<EncuestaIpsRespLiteral>();
            this.EncuestaIpsRespPregunta = new HashSet<EncuestaIpsRespPregunta>();
        }
    
        public int idEncuestaIps { get; set; }
        public System.DateTime fechaHoraEncuestaIps { get; set; }
        public int idFuanAfiliado { get; set; }
        public int idIps { get; set; }
        public string observacionEncuestaIps { get; set; }
        public int idUsuario { get; set; }
    
        public virtual FuanAfiliado FuanAfiliado { get; set; }
        public virtual Ips Ips { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaIpsRespLiteral> EncuestaIpsRespLiteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaIpsRespPregunta> EncuestaIpsRespPregunta { get; set; }
    }
}
