//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaLiteral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaLiteral()
        {
            this.EncuestaEpsRespLiteral = new HashSet<EncuestaEpsRespLiteral>();
            this.EncuestaIpsRespLiteral = new HashSet<EncuestaIpsRespLiteral>();
        }
    
        public short idEncuestaLiteral { get; set; }
        public short idEncuestaPregunta { get; set; }
        public string liteEncuestaLiteral { get; set; }
        public string textoEncuestaLiteral { get; set; }
        public Nullable<byte> valorEncuestaLiteral { get; set; }
        public bool checkedEncuestaLiteral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaEpsRespLiteral> EncuestaEpsRespLiteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaIpsRespLiteral> EncuestaIpsRespLiteral { get; set; }
        public virtual EncuestaPregunta EncuestaPregunta { get; set; }
    }
}
