//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaPregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaPregunta()
        {
            this.EncuestaEpsRespPregunta = new HashSet<EncuestaEpsRespPregunta>();
            this.EncuestaIpsRespPregunta = new HashSet<EncuestaIpsRespPregunta>();
            this.EncuestaLiteral = new HashSet<EncuestaLiteral>();
        }
    
        public short idEncuestaPregunta { get; set; }
        public byte idEncuestaCategoria { get; set; }
        public string codigoEncuestaPregunta { get; set; }
        public string textoEncuestaPregunta { get; set; }
        public byte tipoPreEncuestaPregunta { get; set; }
        public Nullable<byte> valorEncuestaPregunta { get; set; }
    
        public virtual EncuestaCategoria EncuestaCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaEpsRespPregunta> EncuestaEpsRespPregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaIpsRespPregunta> EncuestaIpsRespPregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaLiteral> EncuestaLiteral { get; set; }
    }
}
