//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuanAnexos
    {
        public int idFuan { get; set; }
        public bool anexo56FuanAnexos { get; set; }
        public Nullable<byte> anexo56CNFuanAnexos { get; set; }
        public Nullable<byte> anexo56RCFuanAnexos { get; set; }
        public Nullable<byte> anexo56TIFuanAnexos { get; set; }
        public Nullable<byte> anexo56CCFuanAnexos { get; set; }
        public Nullable<byte> anexo56PAFuanAnexos { get; set; }
        public Nullable<byte> anexo56CEFuanAnexos { get; set; }
        public Nullable<byte> anexo56CDFuanAnexos { get; set; }
        public Nullable<byte> anexo56CSFuanAnexos { get; set; }
        public bool anexo57FuanAnexos { get; set; }
        public bool anexo58FuanAnexos { get; set; }
        public bool anexo59FuanAnexos { get; set; }
        public bool anexo60FuanAnexos { get; set; }
        public bool anexo61FuanAnexos { get; set; }
        public bool anexo62FuanAnexos { get; set; }
        public bool anexo63FuanAnexos { get; set; }
        public bool anexo64FuanAnexos { get; set; }
        public bool anexo65FuanAnexos { get; set; }
    
        public virtual Fuan Fuan { get; set; }
    }
}
