//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuanDeclaracionAutorizacion
    {
        public int idFuan { get; set; }
        public byte idDeclaracionAutorizacion { get; set; }
        public bool valorFuanDeclaracionAutorizacion { get; set; }
    
        public virtual Fuan Fuan { get; set; }
        public virtual DeclaracionAutorizacion DeclaracionAutorizacion { get; set; }
    }
}
