//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fuan()
        {
            this.FuanAfiliado = new HashSet<FuanAfiliado>();
            this.FuanDeclaracionAutorizacion = new HashSet<FuanDeclaracionAutorizacion>();
        }
    
        public int idFuan { get; set; }
        public System.DateTime fechaRadicacionFuan { get; set; }
        public byte idTipoTramite { get; set; }
        public byte idTipoAfiliacion { get; set; }
        public byte idTipoRegimen { get; set; }
        public byte idTipoAfiliado { get; set; }
        public byte idTipoCotizante { get; set; }
        public string codigoCotizanteFuan { get; set; }
        public int idUsuario { get; set; }
    
        public virtual TipoAfiliacion TipoAfiliacion { get; set; }
        public virtual TipoAfiliado TipoAfiliado { get; set; }
        public virtual TipoCotizante TipoCotizante { get; set; }
        public virtual TipoRegimen TipoRegimen { get; set; }
        public virtual TipoTramite TipoTramite { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuanAfiliado> FuanAfiliado { get; set; }
        public virtual FuanAnexos FuanAnexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuanDeclaracionAutorizacion> FuanDeclaracionAutorizacion { get; set; }
        public virtual FuanEntidadTerritorial FuanEntidadTerritorial { get; set; }
    }
}
