//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ips()
        {
            this.EncuestaEps = new HashSet<EncuestaEps>();
            this.EncuestaIps = new HashSet<EncuestaIps>();
        }
    
        public int idIps { get; set; }
        public string codigoIps { get; set; }
        public string razonIps { get; set; }
        public byte idTipoIdentificacion { get; set; }
        public string identificacionIps { get; set; }
        public string direccionIps { get; set; }
        public string telefonoIps { get; set; }
        public Nullable<short> idCiudad { get; set; }
        public string representanteIps { get; set; }
        public string nivelIps { get; set; }
        public string contactoIps { get; set; }
        public string emailIps { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaEps> EncuestaEps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaIps> EncuestaIps { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
    }
}
