//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasSubFactorRiesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreguntasSubFactorRiesgo()
        {
            this.IfppirRespuestaFactor = new HashSet<IfppirRespuestaFactor>();
            this.CicloVitalGestante = new HashSet<CicloVitalGestante>();
            this.CicloVitalPreguntasSubFactorRiesgo = new HashSet<CicloVitalPreguntasSubFactorRiesgo>();
        }
    
        public short idPreguntasSubFactorRiesgo { get; set; }
        public byte idSubFactorRiesgo { get; set; }
        public string codigoPreguntasSubFactorRiesgo { get; set; }
        public string descripcionPreguntasSubFactorRiesgo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IfppirRespuestaFactor> IfppirRespuestaFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloVitalGestante> CicloVitalGestante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloVitalPreguntasSubFactorRiesgo> CicloVitalPreguntasSubFactorRiesgo { get; set; }
        public virtual SubFactorRiesgo SubFactorRiesgo { get; set; }
    }
}
