//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purisu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purisu()
        {
            this.MotivoConsulta = new HashSet<MotivoConsulta>();
            this.MotivoContacto = new HashSet<MotivoContacto>();
            this.PiezasInformativas = new HashSet<PiezasInformativas>();
        }
    
        public int idInfoPurisu { get; set; }
        public int idPurisu { get; set; }
        public int idFuanAfiliado { get; set; }
        public string numCarnePurisu { get; set; }
        public Nullable<byte> idTipoVisitaDomiciliaria { get; set; }
        public bool usisPurisu { get; set; }
        public bool ipsPrimariaPurisu { get; set; }
        public bool telefonicaPurisu { get; set; }
        public bool cauPurisu { get; set; }
        public bool actividadExtramuralPurisu { get; set; }
        public Nullable<byte> idProgramaResolucion412 { get; set; }
        public Nullable<byte> idGrupoInteres { get; set; }
        public Nullable<byte> idSeguimientoProgramasIntervencionRiesgo { get; set; }
        public string numAutorizacionPurisu { get; set; }
        public Nullable<byte> idGruposFocales { get; set; }
        public Nullable<byte> idEje { get; set; }
        public Nullable<short> idUnidad { get; set; }
        public Nullable<short> idModulo { get; set; }
        public Nullable<byte> idEje1 { get; set; }
        public Nullable<short> idUnidad1 { get; set; }
        public Nullable<short> idModulo1 { get; set; }
        public string firmaPurisu { get; set; }
    
        public virtual FuanAfiliado FuanAfiliado { get; set; }
        public virtual InfoPurisu InfoPurisu { get; set; }
        public virtual Eje Eje { get; set; }
        public virtual Eje Eje1 { get; set; }
        public virtual GrupoInteres GrupoInteres { get; set; }
        public virtual GruposFocales GruposFocales { get; set; }
        public virtual Modulo Modulo { get; set; }
        public virtual Modulo Modulo1 { get; set; }
        public virtual ProgramaResolucion412 ProgramaResolucion412 { get; set; }
        public virtual SeguimientoProgramasIntervencionRiesgo SeguimientoProgramasIntervencionRiesgo { get; set; }
        public virtual TipoVisitaDomiciliaria TipoVisitaDomiciliaria { get; set; }
        public virtual Unidad Unidad { get; set; }
        public virtual Unidad Unidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivoConsulta> MotivoConsulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivoContacto> MotivoContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PiezasInformativas> PiezasInformativas { get; set; }
    }
}
