//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFactorRiesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubFactorRiesgo()
        {
            this.PreguntasSubFactorRiesgo = new HashSet<PreguntasSubFactorRiesgo>();
        }
    
        public byte idSubFactorRiesgo { get; set; }
        public byte idFactorRiesgo { get; set; }
        public string codigoSubFactorRiesgo { get; set; }
        public string nombreSubFactorRiesgo { get; set; }
    
        public virtual FactorRiesgo FactorRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntasSubFactorRiesgo> PreguntasSubFactorRiesgo { get; set; }
    }
}
