//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNovedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoNovedad()
        {
            this.FuanTipoNovedad = new HashSet<FuanTipoNovedad>();
        }
    
        public byte idTipoNovedad { get; set; }
        public string codigoTipoNovedad { get; set; }
        public string nombreTipoNovedad { get; set; }
        public string tipoValorCampoTipoNovedad { get; set; }
        public string valorCampoTipoNovedad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuanTipoNovedad> FuanTipoNovedad { get; set; }
    }
}
