//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.GestorReportes.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSexo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoSexo()
        {
            this.FuanAfiliado = new HashSet<FuanAfiliado>();
            this.FuanAfiliado1 = new HashSet<FuanAfiliado>();
            this.FuanBeneficiariosAfiliado = new HashSet<FuanBeneficiariosAfiliado>();
            this.CicloVitalPreguntasSubFactorRiesgo = new HashSet<CicloVitalPreguntasSubFactorRiesgo>();
        }
    
        public byte idTipoSexo { get; set; }
        public string codigoTipoSexo { get; set; }
        public string nombreTipoSexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuanAfiliado> FuanAfiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuanAfiliado> FuanAfiliado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuanBeneficiariosAfiliado> FuanBeneficiariosAfiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CicloVitalPreguntasSubFactorRiesgo> CicloVitalPreguntasSubFactorRiesgo { get; set; }
    }
}
